#!/usr/bin/env python3
"""
3D JSBSim flight log visualizer (matplotlib)

Reads the CSV generated by the toy runner and animates a 3D scene:
- Ground track and altitude (3D)
- Live aircraft marker with body-axis triad (roll/pitch/yaw)
- Altitude strip with moving time cursor (fixed: set_data expects sequences)
- Optional MP4 export

Usage:
  python visualize_3d_flight.py --csv output/jsbsim/toy/run.csv
Options:
  --speed 1.0            # sim seconds / real second
  --tail-seconds 30       # trail length
  --interval 33           # ms per frame (≈30 FPS)
  --save-mp4 flight.mp4   # export video
  --dpi 150               # video DPI
"""

import argparse
import math
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 - activates 3D

R_EARTH = 6371000.0  # meters


def latlon_to_local_xy(lat_deg, lon_deg, lat0_deg, lon0_deg):
    lat = np.radians(lat_deg)
    lon = np.radians(lon_deg)
    lat0 = math.radians(lat0_deg)
    lon0 = math.radians(lon0_deg)
    x = (lon - lon0) * math.cos(lat0) * R_EARTH  # East
    y = (lat - lat0) * R_EARTH  # North
    return x, y


def zyx_euler_to_rot(psi_deg, theta_deg, phi_deg):
    """Rotation matrix R = Rz(psi) * Ry(theta) * Rx(phi), ENU with z up.
    psi: yaw/heading (0=N, +cw to East), theta: pitch up +, phi: roll right wing down +.
    """
    ps = math.radians(psi_deg)
    th = math.radians(theta_deg)
    ph = math.radians(phi_deg)

    cψ, sψ = math.cos(ps), math.sin(ps)
    cθ, sθ = math.cos(th), math.sin(th)
    cφ, sφ = math.cos(ph), math.sin(ph)

    Rz = np.array([[cψ, -sψ, 0], [sψ, cψ, 0], [0, 0, 1]])
    Ry = np.array([[cθ, 0, sθ], [0, 1, 0], [-sθ, 0, cθ]])
    Rx = np.array([[1, 0, 0], [0, cφ, -sφ], [0, sφ, cφ]])
    return Rz @ Ry @ Rx


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, help="CSV from toy runner")
    ap.add_argument("--speed", type=float, default=1.0)
    ap.add_argument("--tail-seconds", type=float, default=30.0)
    ap.add_argument("--interval", type=int, default=33)
    ap.add_argument("--save-mp4", type=str, default=None)
    ap.add_argument("--dpi", type=int, default=150)
    return ap.parse_args()


def main():
    args = parse_args()
    csv_path = Path(args.csv)
    if not csv_path.exists():
        raise SystemExit(f"CSV not found: {csv_path}")

    df = pd.read_csv(csv_path).sort_values("time_s").drop_duplicates(subset=["time_s"])
    t = df["time_s"].to_numpy()
    lat = df["lat_deg"].to_numpy()
    lon = df["lon_deg"].to_numpy()
    alt = df["alt_msl_m"].to_numpy()
    psi = df.get("psi_hdg_deg", 0.0).to_numpy()
    theta = df.get("theta_pitch_deg", 0.0).to_numpy()
    phi = df.get("phi_roll_deg", 0.0).to_numpy()
    tas = df.get("tas_mps", 0.0).to_numpy()

    # Local frame (ENU): x=East, y=North, z=Up
    x, y = latlon_to_local_xy(lat, lon, lat[0], lon[0])
    z = alt

    # Normalize time
    t = t - t[0]

    # Figure layout: 3D main + altitude strip
    fig = plt.figure(figsize=(11, 7))
    gs = fig.add_gridspec(2, 2, height_ratios=[3, 1])
    ax3d = fig.add_subplot(gs[0, :], projection="3d")
    ax_alt = fig.add_subplot(gs[1, :])

    # 3D bounds & ground grid
    xmin, xmax = np.min(x), np.max(x)
    ymin, ymax = np.min(y), np.max(y)
    zmin, zmax = np.min(z), np.max(z)

    # add margins
    def pad(lo, hi, frac=0.08):
        span = max(1.0, hi - lo)
        return lo - frac * span, hi + frac * span

    xmin, xmax = pad(xmin, xmax)
    ymin, ymax = pad(ymin, ymax)
    zmin, zmax = pad(zmin, zmax)

    ax3d.set_xlim(xmin, xmax)
    ax3d.set_ylim(ymin, ymax)
    ax3d.set_zlim(zmin, zmax)
    ax3d.set_xlabel("East [m]")
    ax3d.set_ylabel("North [m]")
    ax3d.set_zlabel("Alt MSL [m]")
    ax3d.set_title("3D Flight View")

    # Draw a simple ground grid at z=zmin
    grid_e = np.linspace(xmin, xmax, 12)
    grid_n = np.linspace(ymin, ymax, 12)
    for xe in grid_e:
        ax3d.plot([xe, xe], [ymin, ymax], [zmin, zmin], lw=0.5, alpha=0.2)
    for yn in grid_n:
        ax3d.plot([xmin, xmax], [yn, yn], [zmin, zmin], lw=0.5, alpha=0.2)

    # Static faint full path
    ax3d.plot(x, y, z, lw=1, alpha=0.15)

    # Dynamic trail + live point + body-axis triad
    (trail_line,) = ax3d.plot([], [], [], lw=2)
    (point_marker,) = ax3d.plot([], [], [], marker="o", ms=6)
    # body axes (forward, right, up) lines
    (body_fwd_line,) = ax3d.plot([], [], [], lw=2)
    (body_right_line,) = ax3d.plot([], [], [], lw=2)
    (body_up_line,) = ax3d.plot([], [], [], lw=2)

    # Altitude strip
    ax_alt.set_title("Altitude vs Time")
    ax_alt.set_xlabel("Time [s]")
    ax_alt.set_ylabel("MSL Altitude [m]")
    ax_alt.plot(t, z, lw=1, alpha=0.6)
    ymin_alt, ymax_alt = ax_alt.get_ylim()
    # vertical cursor (fix: set_data wants sequences)
    alt_cursor_line = ax_alt.plot(
        [t[0], t[0]], [ymin_alt, ymax_alt], linestyle="--", lw=1
    )[0]

    # Frame scheduling
    dt_sim_per_frame = args.speed * (args.interval / 1000.0)
    frame_times = np.arange(t[0], t[-1] + dt_sim_per_frame, dt_sim_per_frame)
    indices = np.searchsorted(t, frame_times, side="left")
    indices = np.clip(indices, 0, len(t) - 1)

    # scale for body-axis glyph
    # base on local motion scale or altitude span
    path_scale = max(1.0, 0.05 * max(xmax - xmin, ymax - ymin))
    triad_len = max(10.0, 0.15 * path_scale)

    info_txt = ax3d.text2D(
        0.02, 0.98, "", transform=ax3d.transAxes, va="top", ha="left"
    )

    def update(frame_idx):
        i = indices[frame_idx]
        ti = t[i]
        xi, yi, zi = x[i], y[i], z[i]
        ψi, θi, φi = float(psi[i]), float(theta[i]), float(phi[i])
        tasi = float(tas[i])

        # Trail window
        t_start = ti - args.tail_seconds
        if t_start <= t[0]:
            mask = t <= ti
        else:
            mask = (t >= t_start) & (t <= ti)

        trail_line.set_data_3d(x[mask], y[mask], z[mask])
        point_marker.set_data_3d([xi], [yi], [zi])

        # Body axes from Euler ZYX
        R = zyx_euler_to_rot(ψi, θi, φi)
        origin = np.array([xi, yi, zi])
        fwd = origin + R @ np.array([triad_len, 0.0, 0.0])  # x_b (forward)
        rgt = origin + R @ np.array([0.0, triad_len * 0.7, 0.0])  # y_b (right)
        upv = origin + R @ np.array([0.0, 0.0, triad_len * 0.5])  # z_b (up)

        body_fwd_line.set_data_3d(
            [origin[0], fwd[0]], [origin[1], fwd[1]], [origin[2], fwd[2]]
        )
        body_right_line.set_data_3d(
            [origin[0], rgt[0]], [origin[1], rgt[1]], [origin[2], rgt[2]]
        )
        body_up_line.set_data_3d(
            [origin[0], upv[0]], [origin[1], upv[1]], [origin[2], upv[2]]
        )

        # Alt strip cursor (fix)
        ymin_alt, ymax_alt = ax_alt.get_ylim()
        alt_cursor_line.set_data([ti, ti], [ymin_alt, ymax_alt])

        info_txt.set_text(
            f"t = {ti:6.2f} s\n"
            f"ALT = {zi:7.1f} m\n"
            f"TAS = {tasi:6.1f} m/s\n"
            f"ψ={ψi:5.1f}°, θ={θi:5.1f}°, φ={φi:5.1f}°"
        )

        return (
            trail_line,
            point_marker,
            body_fwd_line,
            body_right_line,
            body_up_line,
            alt_cursor_line,
            info_txt,
        )

    ani = FuncAnimation(
        fig, update, frames=len(indices), interval=args.interval, blit=False
    )

    if args.save_mp4:
        out = Path(args.save_mp4)
        print(f"[INFO] Saving MP4 to {out} …")
        writer = FFMpegWriter(fps=max(1, int(1000 / args.interval)))
        ani.save(str(out), writer=writer, dpi=args.dpi)
        print(f"[OK] Saved: {out}")

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
